In [7]:
import numpy as np
from numpy.linalg import qr

# Example matrix A
a = np.array([[2, 2, 4],
              [1, 3, 5],
              [2, 3, 4]])

# Perform QR decomposition
q, r = qr(a)
print('Q:', q)
print('R:', r)

# Verify that A = QR
b = np.dot(q, r)
eigenvalues_iter1 = np.diag(b)
print('QR:', b)

print(eigenvalues_iter1)

Q: [[-0.66666667  0.49518757 -0.55708601]
 [-0.33333333 -0.86657824 -0.37139068]
 [-0.66666667 -0.06189845  0.74278135]]
R: [[-3.         -4.33333333 -7.        ]
 [ 0.         -1.79505494 -2.59973473]
 [ 0.          0.         -1.11417203]]
QR: [[2. 2. 4.]
 [1. 3. 5.]
 [2. 3. 4.]]
[2. 3. 4.]


In [8]:
import numpy as np

# Define the matrix
A = np.array([[2, 2, 4],
              [1, 3, 5],
              [2, 3, 4]])

# Perform 1 iteration of the QR method
Q, R = np.linalg.qr(A)
A = np.dot(Q, R)
eigenvalues_iter1 = np.diag(A)
print("Eigenvalues after 1 iteration:", eigenvalues_iter1)

# Perform 10 iterations of the QR method
for i in range(9):  # Iterate 9 more times (total 10 iterations)
    Q, R = np.linalg.qr(A)
    A = np.dot(R, Q)
eigenvalues_iter10 = np.diag(A)
print("Eigenvalues after 10 iterations:", eigenvalues_iter10)

# Perform 10 more iterations of the QR method
for i in range(10):  # Iterate 10 times more (total 20 iterations)
    Q, R = np.linalg.qr(A)
    A = np.dot(R, Q)
eigenvalues_iter20 = np.diag(A)
print("Eigenvalues after 20 iterations:", eigenvalues_iter20)


Eigenvalues after 1 iteration: [2. 3. 4.]
Eigenvalues after 10 iterations: [ 8.80916361  0.91668029 -0.72584391]
Eigenvalues after 20 iterations: [ 8.80916362  0.92531542 -0.73447904]
