In [1]:
import numpy as np

In [2]:
def gaussian_elimination(matrix, vector):
    # Reshape the vector into a column vector
    vector = np.reshape(vector, (-1, 1))
    
    # Convert the matrix data type to float
    matrix = matrix.astype(float)
    vector = vector.astype(float)

    # Construct the augmented matrix
    augmented_matrix = np.hstack((matrix, vector))

    # Get the number of rows and columns of the matrix
    rows, cols = augmented_matrix.shape
        # Main loop of Gaussian elimination
    for i in range(rows):
        # If the diagonal element is zero, perform row swaps
        if augmented_matrix[i, i] == 0:
            for k in range(i + 1, rows):
                if augmented_matrix[k, i] != 0:
                    augmented_matrix[[i, k]] = augmented_matrix[[k, i]]
                    break
  
        # Set other elements in the column to zero
        for k in range(i + 1, rows):
            factor = augmented_matrix[k, i] / augmented_matrix[i, i]
            augmented_matrix[k] -= factor * augmented_matrix[i]

    # Output the upper triangular matrix
    print("Upper Triangular Matrix:")
    for i in range(rows):
        print(augmented_matrix[i][:cols])

    # Back substitution process to solve the system of equations
    solution = np.zeros(rows)
    for i in range(rows - 1, -1, -1):
        solution[i] = (augmented_matrix[i, -1] - np.dot(augmented_matrix[i, i + 1:rows], solution[i + 1:])) / augmented_matrix[i, i]

    print(solution)

In [3]:
# Test Gaussian elimination

#Sample1
a = np.array([[1, 2, 3], [3, 4, 5], [3, 5, 5]])
y = np.array([2, 2, 5])

solution = gaussian_elimination(a, y)

 
#Sample 2 
a = np.array([[1, 2, 3, 4],[5, 4, 3, 2],[2, 1, 2, 4],[2, 1, 3, 4]]) 
y = np.array([4, 8, 5, 6]) 

solution = gaussian_elimination(a, y)

Upper Triangular Matrix:
[1. 2. 3. 2.]
[ 0. -2. -4. -4.]
[ 0.  0. -2.  1.]
[-2.5  3.  -0.5]
Upper Triangular Matrix:
[1. 2. 3. 4. 4.]
[  0.  -6. -12. -18. -12.]
[0. 0. 2. 5. 3.]
[ 0.   0.   0.  -2.5 -0.5]
[ 1.4 -0.6  1.   0.2]
